### ISSUE TITLE
Feature request: whitelist

### ISSUE THREAD

**Issue by mrbluecoat** [relekang/coredns-blocklist#11]
Can you add a whitelist capability that takes precedence over the blacklist? Something like

```
. {
  log
  prometheus

  whitelist mywhitelistfile.txt

  # load from url
  blocklist https://mirror1.malwaredomains.com/files/justdomains
  # load from file, if the path is not absolute it will be relative to the Corefile
  blocklist list.txt

  forward . 1.1.1.1 1.0.0.1
}
```

**Comment by relekang** [comment]
I'm happy to accept a PR for it if it is called allowlist. I think it would have to be as part of the blocklist statement like

```
blocklist {
  block block.txt
  allow allow.txt
}
```

**Comment by mutemule** [comment]
FYI, I've started to work on this in [my fork](https://github.com/mutemule/coredns-blocklist/tree/allowlist). There are a few things that I figure are worth discussing before i get too far into this:

1. If a DNS RR should be both blocked and allowed, it will always be allowed, regardless of domain specificity. This means that if you have allowed "example.com", and "foo.bar.baz.example.com" is in your blocklist, the query will be allowed.
2. It introduces a distinct counter that is for domains that were _not_ blocked because of your allowlist. These counters will only be incremented if the RR exists in both the blocklist and the allowlist, and will _not_ be incremented if the RR only exists in the allowlist.
3. It's one allowlist per `blocklist` configuration block. This means that if you have multiple allowlist sources, you need to merge them into one to pass in to your `blocklist` configuration stanza. It also means that you can selectively apply your allowlist to a given `blocklist` -- i.e. you can have a blocklist that is never overridden.
4. It's going to follow the approach to children as was introduced in #12: a given DNS query will match any parent of that name. So if you have `example.com` in your allowlist, `foo.bar.example.com` will be allowed.

**Comment by mutemule** [comment]
> I think it would have to be as part of the blocklist statement

I'd agree with that: the way CoreDNS plugins are set up, if you want to have an `allowlist` configuration stanza, then you need an `allowlist` plugin. And now we need to share configuration data across plugins, or otherwise tag queries with a special value that is passed down to later plugins.

And while that tagging approach likely has a certain amount of value, that's something I'd like to see come out of the CoreDNS project proper. By far the simplest approach is to keep the `allowlist` overrides within a `blocklist` stanza.

**Comment by relekang** [comment]
@mutemule Sounds great 😃
